on:
  pull_request:
    branches: [ "eevee" ]

jobs:
  my_job:
    name: deploy to eevee
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
         node-version: '10.x'
      - name: Install Dependencies
        run: |
         npm install
         npm run build
